### PR TITLE
Add GitHub workflows

### LINKED ISSUE #106: Move to GitHub Actions
Travis no longer provides free plan for OSS.

It should be based on https://github.com/chalk/chalk/blob/main/.github/workflows/main.yml, but made to work with Atom.

### PR DESCRIPTION
**Pull request by BarryThePenguin**
Fixes #106

I've based this off https://github.com/atom/ci and their example workflow https://github.com/atom/ci/blob/master/.github/workflows/main.yml

~~Currently trying to figure out how to run the workflows from a fork~~ 👀

Looks like the action ran for the branch https://github.com/BarryThePenguin/atom-linter-xo/actions/runs/829724285

I'll spend some time looking at getting a windows build running, but happy to be given direction there..

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for doing this :)

**Comment by sindresorhus** [comment]
Hmm, seems to be failing on Windows now: https://github.com/xojs/atom-linter-xo/runs/2555331222?check_suite_focus=true

**Comment by BarryThePenguin** [comment]
Maybe I wasn't very clear 😅 I spent some time looking into it, but wasn't able to get a windows build running.. You can see the [workflow results from my fork](https://github.com/BarryThePenguin/atom-linter-xo/actions)

From what I can understand, it's failing while installing https://github.com/atom/superstring
It appears `node-gyp` is trying to use Visual Studio 2015, but the [GitHub Actions Windows environment](https://github.com/actions/virtual-environments#available-environments) only support a minimum of Visual Studio 2017

I'd probably consider removing the windows builds from the build matrix

**Comment by sindresorhus** [comment]
Ah ok. I did indeed miss that.

**Pull request merged**
